name: Cypress Tests

on: [push, pull_request]
  
jobs:
  run-chrome-tests:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        containers: [1, 2, 3] 
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.3.0
      - name: Run Tests In Cloud
        uses: cypress-io/github-action@v5.0.9
        with: 
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          
