name: Cypress Tests
  
  on: [pull_request]
  
  jobs: 
    name: Cypress Tests With Chrome
    runs-on: ubuntu-latest
    steps: 
      - name: Git Checkout 
        uses: uses: actions/checkout@v3.3.0
      - name: Install Dependencies
        run: yarn install
      - name: Run E2E tests
        run: yarn cypress run
    
    
