name: Cypress Tests

on: [push, pull_request]
  
jobs:
  run-chrome-tests:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        containers: [1, 2, 3] 
    container:
      image: cypress/base:12
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.3.0
      - name: Run Tests In Cloud
        uses: cypress-io/github-action@v5.0.9
        with: 
          command-install: yarn install
          record: true
          parallel: true
          browser: chrome
          group: UI Chrome
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
  
  run-electron-tests:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        containers: [1, 2, 3] 
    container:
      image: cypress/base:12
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.3.0
      - name: Run Tests In Cloud
        uses: cypress-io/github-action@v5.0.9
        with: 
          command-install: yarn install
          record: true
          parallel: true
          browser: electron
          group: UI Electron
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          
